package ventana;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JhordaNN
 */
public class ventanaConvertidor extends javax.swing.JFrame {
      private String divisa1="";
      private String divisa2="";


    public ventanaConvertidor() {
        initComponents();
        setSize(300, 450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaDivisa1 = new javax.swing.JLabel();
        etiquetaDivisa2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        monedaInicial = new javax.swing.JTextField();
        monedaFinal = new javax.swing.JTextField();
        botonConvertir = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        convertidorDeDivisas = new javax.swing.JMenuItem();
        cronometro = new javax.swing.JMenuItem();
        convertidorDeTemperatura = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor de divisas");
        setPreferredSize(new java.awt.Dimension(300, 450));
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaDivisa1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        etiquetaDivisa1.setText("Moneda Origen");
        panel.add(etiquetaDivisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 87, -1, 30));

        etiquetaDivisa2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        etiquetaDivisa2.setText("Moneda Destino");
        panel.add(etiquetaDivisa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 169, -1, 29));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Sol", "Euro", "Libra Esterlina", "Yen Japonés", "Won sul-coreano" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 129, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Sol", "Euro", "Libra Esterlina", "Yen Japonés", "Won sul-coreano" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        panel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 211, -1, -1));

        monedaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaInicialActionPerformed(evt);
            }
        });
        panel.add(monedaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 129, 111, -1));

        monedaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaFinalActionPerformed(evt);
            }
        });
        panel.add(monedaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 211, 111, -1));

        botonConvertir.setText("Convertir");
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });
        botonConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonConvertirKeyPressed(evt);
            }
        });
        panel.add(botonConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 284, -1, -1));

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        panel.add(botonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 284, -1, -1));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dtransparente.png"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 410));

        jMenu1.setText("Usos");

        convertidorDeDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/divisas (2).png"))); // NOI18N
        convertidorDeDivisas.setText("Convertidor De Divisas");
        jMenu1.add(convertidorDeDivisas);

        cronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cronometro.png"))); // NOI18N
        cronometro.setText("Cronometro");
        cronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cronometroActionPerformed(evt);
            }
        });
        jMenu1.add(cronometro);

        convertidorDeTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/temperatura.png"))); // NOI18N
        convertidorDeTemperatura.setText("Convertidor De Temperatura");
        convertidorDeTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertidorDeTemperaturaActionPerformed(evt);
            }
        });
        jMenu1.add(convertidorDeTemperatura);
        jMenu1.add(jSeparator1);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void monedaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaInicialActionPerformed
             
    }//GEN-LAST:event_monedaInicialActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        divisa1 = (String)jComboBox1.getSelectedItem();
         
	

          switch (divisa1) {
              case "Dolar" -> etiquetaDivisa1.setText("$");
              case "Sol" -> etiquetaDivisa1.setText("S/.");
              case "Euro" -> etiquetaDivisa1.setText("€");
              case "Libra Esterlina" -> etiquetaDivisa1.setText("£");
              case "Yen Japonés" -> etiquetaDivisa1.setText("¥");
              case "Won sul-coreano" -> etiquetaDivisa1.setText("₩");
              default -> {
              }
                               
          }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
                divisa2 = (String)jComboBox2.getSelectedItem();
                
          switch (divisa2) {
              case "Dolar" -> etiquetaDivisa2.setText("$");
              case "Sol" -> etiquetaDivisa2.setText("S/.");
              case "Euro" -> etiquetaDivisa2.setText("€");
              case "Libra Esterlina" -> etiquetaDivisa2.setText("£");
              case "Yen Japonés" -> etiquetaDivisa2.setText("¥");
              case "Won sul-coreano" -> etiquetaDivisa2.setText("₩");
              default -> {
              }
          }
         
	

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void botonConvertirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonConvertirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConvertirKeyPressed

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
  String inputText = monedaInicial.getText();

//De Dolar a ... 
try{
        if(divisa1 == "Dolar" && divisa2 == "Euro"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.93985; // tasa de cambio de USD a EUR
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
        else if(divisa1 == "Dolar" && divisa2 == "Sol"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 3.77; // tasa de cambio de USD a Soles
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Dolar" && divisa2 == "Libra Esterlina"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.82160143; // tasa de cambio de Dolar a Libra Esterlina
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
        else if(divisa1 == "Dolar" && divisa2 == "Yen Japonés"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =134.23688 ; // tasa de cambio de Dolar a Libra Esterlina
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Dolar" && divisa2 == "Won sul-coreano"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =1300.2411; // tasa de cambio de Dolar a Libra Esterlina
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}           
        else if(divisa1 == "Dolar" && divisa2 == "Dolar"){
        monedaFinal.setText(inputText);}  
//De Euros a ...         
        else if(divisa1 == "Euro" && divisa2 == "Dolar"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 1.06711; // tasa de cambio de euros a dolares
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Euro" && divisa2 == "Sol"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 1.06711; // tasa de cambio de euros a soles
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");} 
        else if(divisa1 == "Euro" && divisa2 == "Libra Esterlina"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 1397.87; // tasa de cambio de euro a Libra Esterlina
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
        else if(divisa1 == "Euro" && divisa2 == "Yen Japonés"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =144.351 ; // tasa de cambio de euro a yen
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Euro" && divisa2 == "Won sul-coreano"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =1397.25; // tasa de cambio de euro a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}            
        else if(divisa1 == "Euro" && divisa2 == "Euro"){
        monedaFinal.setText(inputText);}        
//De Soles a ... 
        else if(divisa1 == "Sol" && divisa2 == "Dolar"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.26; // tasa de cambio de soles a dolar
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");         
        }
        else if(divisa1 == "Sol" && divisa2 == "Euro"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.25; // tasa de cambio de euros a soles
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
        else if(divisa1 == "Sol" && divisa2 == "Libra Esterlina"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.216624; // tasa de cambio de sol a Libra Esterlina
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
        else if(divisa1 == "Sol" && divisa2 == "Yen Japonés"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =35.4111 ; // tasa de cambio de sol a yen
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Sol" && divisa2 == "Won sul-coreano"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =342.818 ; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}              
        else if(divisa1 == "Sol" && divisa2 == "Sol"){
        monedaFinal.setText(inputText);}
        
//De Libra Esterlina a ... 
        else if(divisa1 == "Libra Esterlina" && divisa2 == "Dolar"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 1.21725; // tasa de cambio de soles a dolar
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");         
        }
        else if(divisa1 == "Libra Esterlina" && divisa2 == "Euro"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 1.13231; // tasa de cambio de euros a soles
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
        else if(divisa1 == "Libra Esterlina" && divisa2 == "Yen Japonés"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =163.465; // tasa de cambio de sol a yen
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Libra Esterlina" && divisa2 == "Sol"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =4.61638; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}           
        else if(divisa1 == "Libra Esterlina" && divisa2 == "Won sul-coreano"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =1583.05; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}              
        else if(divisa1 == "Libra Esterlina" && divisa2 == "Libra Esterlina"){
        monedaFinal.setText(inputText);}       
//De Yen Japonés a ... 
        else if(divisa1 == "Yen Japonés" && divisa2 == "Dolar"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.007446; // tasa de cambio de soles a dolar
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");         
        }
        else if(divisa1 == "Yen Japonés" && divisa2 == "Sol"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =0.003; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}   
        else if(divisa1 == "Yen Japonés" && divisa2 == "Libra Esterlina"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =0.000632; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}          
        else if(divisa1 == "Yen Japonés" && divisa2 == "Euro"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.007; // tasa de cambio de euros a soles
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
  
        else if(divisa1 == "Yen Japonés" && divisa2 == "Won sul-coreano"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =9.68269; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}              
        else if(divisa1 == "Yen Japonés" && divisa2 == "Yen Japonés"){
        monedaFinal.setText(inputText);}                 
//De Won sul-coreano a ... 
        else if(divisa1 == "Won sul-coreano" && divisa2 == "Dolar"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.007446; // tasa de cambio de soles a dolar
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");         
        }
        else if(divisa1 == "Won sul-coreano" && divisa2 == "Euro"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate = 0.007; // tasa de cambio de euros a soles
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}
  
        else if(divisa1 == "Won sul-coreano" && divisa2 == "Sol"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =9.68269; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");} 
        else if(divisa1 == "Won sul-coreano" && divisa2 == "Libra Esterlina"){
        double inputAmount = Double.parseDouble(inputText );
        double exchangeRate =9.68269; // tasa de cambio de sol a won
        double outputAmount = inputAmount * exchangeRate;
        monedaFinal.setText(outputAmount + "");}         
        else if(divisa1 == "Won sul-coreano" && divisa2 == "Won sul-coreano"){
        monedaFinal.setText(inputText);} 
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Valor no válido. Por favor, introduzca un número.", "Error", JOptionPane.ERROR_MESSAGE);
}        
              
    }//GEN-LAST:event_botonConvertirActionPerformed

    private void monedaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaFinalActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
   monedaInicial.setText("");
    monedaFinal.setText("");  
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void cronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cronometroActionPerformed
       ventanaCronometro cronometro = new ventanaCronometro();
        cronometro.setVisible(true);

        dispose();  //para que se cierre la ventana anterior
    }//GEN-LAST:event_cronometroActionPerformed

    private void convertidorDeTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertidorDeTemperaturaActionPerformed
       ventanaConvertidorT convertidorT = new ventanaConvertidorT();
       convertidorT.setVisible(true);
       
       dispose(); //para que se cierre la ventana anteior
    }//GEN-LAST:event_convertidorDeTemperaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaConvertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonConvertir;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JMenuItem convertidorDeDivisas;
    private javax.swing.JMenuItem convertidorDeTemperatura;
    private javax.swing.JMenuItem cronometro;
    private javax.swing.JLabel etiquetaDivisa1;
    private javax.swing.JLabel etiquetaDivisa2;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField monedaFinal;
    private javax.swing.JTextField monedaInicial;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
