/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
public class ventanaCronometro extends javax.swing.JFrame {
private Timer tiempo; //Timer es una clase
    private int centesimaSegundos=0,segundos=0,minutos=0,horas=0;
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           centesimaSegundos++;
           if(centesimaSegundos == 100){
               segundos++;
               centesimaSegundos=0;
           }
           if(segundos==60){
               minutos++;
               segundos=0;
           }
           if(minutos==60){
               horas++;
               minutos=0;
               
           }
           actualizarEtiquetaTiempo();
        }
    };
        private void actualizarEtiquetaTiempo(){
        //si las horas son menores igual que 9 entonces copiaremos cero, caso contrario copiamos nada 
        String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos+":"+(centesimaSegundos<=9?"0":"")+centesimaSegundos;
        etiquetaTiempo.setText(texto);
    }
    public ventanaCronometro() {
          initComponents();
        setLocationRelativeTo(null);
        tiempo = new Timer(10,acciones);  //cada 10 milisegundos ocurriran las acciones
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaTexto = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        botonPausar = new javax.swing.JButton();
        botonIniciar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        convertidorDeDivisas = new javax.swing.JMenuItem();
        convertidorDeTemperatura = new javax.swing.JMenuItem();
        cronometro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronómetro");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTexto.setFont(new java.awt.Font("Ebrima", 1, 33)); // NOI18N
        etiquetaTexto.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTexto.setText("Cronómetro");
        panel.add(etiquetaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        etiquetaTiempo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 153, 204));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00:00:00:00");
        panel.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 220, 60));

        botonPausar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonPausar.setText("Pausar");
        botonPausar.setToolTipText("");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        botonIniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonIniciar.setText("Inicio");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panel.add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        botonDetener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonDetener.setText("Detener");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ocean-3605547_1280 (2).jpg"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Usos");

        convertidorDeDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/divisas (2).png"))); // NOI18N
        convertidorDeDivisas.setText("Convertidor De Divisas");
        convertidorDeDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertidorDeDivisasActionPerformed(evt);
            }
        });
        jMenu1.add(convertidorDeDivisas);

        convertidorDeTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/temperatura.png"))); // NOI18N
        convertidorDeTemperatura.setText("Convertidor De Temperatura");
        convertidorDeTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertidorDeTemperaturaActionPerformed(evt);
            }
        });
        jMenu1.add(convertidorDeTemperatura);

        cronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cronometro.png"))); // NOI18N
        cronometro.setText("Cronometro");
        cronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cronometroActionPerformed(evt);
            }
        });
        jMenu1.add(cronometro);
        jMenu1.add(jSeparator1);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertidorDeDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertidorDeDivisasActionPerformed
        ventanaConvertidor conversor = new ventanaConvertidor();
        conversor.setVisible(true);

        dispose();  //para que se cierre la ventana anterior
    }//GEN-LAST:event_convertidorDeDivisasActionPerformed

    private void convertidorDeTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertidorDeTemperaturaActionPerformed
        ventanaConvertidorT convertidorT = new ventanaConvertidorT();
        convertidorT.setVisible(true);

        dispose(); //para cerrar la ventana anterior
    }//GEN-LAST:event_convertidorDeTemperaturaActionPerformed

    private void cronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cronometroActionPerformed
        ventanaCronometro cronometro = new ventanaCronometro();
        cronometro.setVisible(true);

        dispose();  //para que se cierre la ventana anterior
    }//GEN-LAST:event_cronometroActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        tiempo.stop();
        botonIniciar.setEnabled(true);
        botonPausar.setEnabled(false);

    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tiempo.start();
        botonIniciar.setEnabled(false);
        botonIniciar.setText("Reanudar");
        botonPausar.setEnabled(true);
        botonDetener.setEnabled(true);
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        if(tiempo.isRunning()){
            tiempo.stop();
            botonIniciar.setEnabled(true);
        }
        botonIniciar.setText("Iniciar");
        botonPausar.setEnabled(false);
        botonDetener.setEnabled(false);

        horas=0;
        minutos=0;
        segundos=0;
        centesimaSegundos=0;

        //para que se limpe
        actualizarEtiquetaTiempo();

    }//GEN-LAST:event_botonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaCronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JMenuItem convertidorDeDivisas;
    private javax.swing.JMenuItem convertidorDeTemperatura;
    private javax.swing.JMenuItem cronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaTexto;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
